### ISSUE TITLE
Request: Disable "Disarm" enchant

### ISSUE THREAD

**Issue by EverNife** [KryptonCaptain/Thaumic_Exploration#2]
I don't know if you accept suggestions, but...

If you could do this it would help me a lot.

A config option to disable the "Disarm" enchant, as this one can be really game-breaking into specific servers ✌️

**Comment by KryptonCaptain** [comment]
Done and done. Pick it up from Releases whenever

**Comment by KryptonCaptain** [comment]
Though, I am curious what the actual issue with it is, if you could explain

**Comment by EverNife** [comment]
I use CustomNpcs as bosses into my server, and my bosses have good weapons (draconic sword for exemple, as well as my own custom ones).

When players with this enchant go aggainst them they can be picking up these weapons T.T

Thats my issue ^^
